hardcoded_data = [
    {
        "city": "Kyoto",
        "fly_to": "KIX",
        "fly_from": "LYS",
        "date_from": "19/02/2023",
        "date_to": "17/08/2023",
        "nights_in_dst_from": 60,
        "nights_in_dst_to": 90,
        "max_fly_duration": 23,
        "flight_type": "round",
        "ret_from_diff_city": False,
        "ret_to_diff_city": False,
        "selected_cabins": "M",
        "adult_hold_bag": 1,
        "price_to": "",
        "curr": "EUR",
        "max_stopovers": "",
        "max_sector_stopovers": 1,
        "limit": 5,
        "id": 2
    },
    {
        "city": "Fukuoka",
        "fly_to": "FUK",
        "fly_from": "LYS",
        "date_from": "19/02/2023",
        "date_to": "17/08/2023",
        "nights_in_dst_from": 60,
        "nights_in_dst_to": 90,
        "max_fly_duration": 23,
        "flight_type": "round",
        "ret_from_diff_city": False,
        "ret_to_diff_city": False,
        "selected_cabins": "M",
        "adult_hold_bag": 1,
        "price_to": "",
        "curr": "EUR",
        "max_stopovers": "",
        "max_sector_stopovers": 1,
        "limit": 5,
        "id": 3
    },
    {
        "city": "Tokyo",
        "fly_to": "TYO",
        "fly_from": "LYS",
        "date_from": "19/02/2023",
        "date_to": "17/08/2023",
        "nights_in_dst_from": 60,
        "nights_in_dst_to": 90,
        "max_fly_duration": 23,
        "flight_type": "round",
        "ret_from_diff_city": False,
        "ret_to_diff_city": False,
        "selected_cabins": "M",
        "adult_hold_bag": 1,
        "price_to": "",
        "curr": "EUR",
        "max_stopovers": "",
        "max_sector_stopovers": 1,
        "limit": 5,
        "id": 4
    },
    {
        "city": "Taipei",
        "fly_to": "TPE",
        "fly_from": "LYS",
        "date_from": "19/02/2023",
        "date_to": "17/08/2023",
        "nights_in_dst_from": 30,
        "nights_in_dst_to": 90,
        "max_fly_duration": 23,
        "flight_type": "round",
        "ret_from_diff_city": False,
        "ret_to_diff_city": False,
        "selected_cabins": "M",
        "adult_hold_bag": 1,
        "price_to": "",
        "curr": "EUR",
        "max_stopovers": "",
        "max_sector_stopovers": 1,
        "limit": 5,
        "id": 5
    },
    {
        "city": "Lisbon",
        "fly_to": "LIS",
        "fly_from": "LYS",
        "date_from": "19/02/2023",
        "date_to": "17/08/2023",
        "nights_in_dst_from": 7,
        "nights_in_dst_to": 30,
        "max_fly_duration": "",
        "flight_type": "round",
        "ret_from_diff_city": False,
        "ret_to_diff_city": False,
        "selected_cabins": "M",
        "adult_hold_bag": "",
        "price_to": "",
        "curr": "EUR",
        "max_stopovers": "",
        "max_sector_stopovers": 0,
        "limit": 5,
        "id": 6
    },
    {
        "city": "Istanbul",
        "fly_to": "IST",
        "fly_from": "LYS",
        "date_from": "19/02/2023",
        "date_to": "17/08/2023",
        "nights_in_dst_from": 7,
        "nights_in_dst_to": 25,
        "max_fly_duration": "",
        "flight_type": "round",
        "ret_from_diff_city": False,
        "ret_to_diff_city": False,
        "selected_cabins": "M",
        "adult_hold_bag": "",
        "price_to": "",
        "curr": "EUR",
        "max_stopovers": "",
        "max_sector_stopovers": 0,
        "limit": 5,
        "id": 7
    },
    {
        "city": "New York",
        "fly_to": "NYC",
        "fly_from": "LYS",
        "date_from": "19/02/2023",
        "date_to": "17/08/2023",
        "nights_in_dst_from": 15,
        "nights_in_dst_to": 60,
        "max_fly_duration": "",
        "flight_type": "round",
        "ret_from_diff_city": False,
        "ret_to_diff_city": False,
        "selected_cabins": "M",
        "adult_hold_bag": "",
        "price_to": "",
        "curr": "EUR",
        "max_stopovers": "",
        "max_sector_stopovers": 1,
        "limit": 5,
        "id": 8
    },
    {
        "city": "Berlin",
        "fly_to": "BER",
        "fly_from": "LYS",
        "date_from": "19/02/2023",
        "date_to": "17/08/2023",
        "nights_in_dst_from": 7,
        "nights_in_dst_to": 31,
        "max_fly_duration": "",
        "flight_type": "round",
        "ret_from_diff_city": False,
        "ret_to_diff_city": False,
        "selected_cabins": "M",
        "adult_hold_bag": "",
        "price_to": "",
        "curr": "EUR",
        "max_stopovers": "",
        "max_sector_stopovers": 0,
        "limit": 5,
        "id": 9
    }
]